/**
 * Brain Products — affiliate / product landing pages auto-generated by
 * CEO Brain. Each entry powers a public /shop/<slug> landing that drives
 * affiliate or direct-purchase revenue.
 *
 * Storage: localStorage on the admin dashboard for now (zero DDL ship).
 * Will migrate to a Supabase `brain_products` table when we move Brain
 * into the brain.markethubpromo.com subdomain (Phase 2).
 *
 * Public surface: /shop/[slug] reads ALL entries from the (future) DB
 * via /api/brain/products (server-side fetch). For now, reads from
 * localStorage in the admin UI and renders a preview.
 */

export interface BrainProduct {
  slug: string;                    // /shop/<slug>
  name: string;                    // "Sennheiser HD 660S Headphones"
  category: string;                // "Audio · Studio gear"
  tagline: string;                 // <100 chars
  hero_h1: string;                 // outcome-driven
  description: string;             // 2-3 paragraph longform pitch
  outcomes: { label: string; body: string }[];   // 3
  steps: { heading: string; body: string }[];    // 3 — "How you'll use it"
  affiliate_url: string;           // cloaked URL (e.g. mkt.link/abc — the actual destination)
  affiliate_program?: string;      // "Amazon Associates" / "Impact" / "Direct"
  image_urls: string[];            // 1-3 product photos (https URLs)
  workflow_kind?: "prompt-to-image" | "text-to-many" | "text-vs-text" | "list-to-buckets" | "voice-clone" | "video-to-text";
  price_display?: string;          // "$429" or "starting at $99/mo"
  badge?: string;                  // "Best Seller" / "Editor's Pick" / "New"
  tags: string[];                  // SEO + filter tags
  generated_at: number;            // Date.now() — when Brain made it
  generated_by?: "brain" | "manual";
}

// Demo seed entries for development / preview — these are illustrative
// and explicitly marked so the public catalog doesn't accidentally
// promote products we didn't actually pick.
export const DEMO_PRODUCTS: BrainProduct[] = [];
