/**
 * Maintenance Agent — Daily Digest Consolidator
 *
 * Reads all unresolved `maintenance_findings`, groups them by severity, and
 * emails a consolidated digest to the admin via Resend. Runs last in the
 * daily GitHub Actions workflow (after probe, schema-drift, consistency).
 *
 * Idempotency: uses a fingerprint `digest:${yyyy-mm-dd}` so re-runs within
 * the same day don't double-send. The finding itself isn't important — it's
 * just a lock row in `maintenance_findings`.
 *
 * Auth: Bearer CRON_SECRET.
 *
 * TODO: Phase 2 will add Haiku-powered prioritization / dedup. For now the
 * email is a simple flat list grouped by severity, which is already more
 * than we had this morning.
 */
import { NextRequest, NextResponse } from "next/server";
import { verifyCronSecret } from "@/lib/cronAuth";
import { createServiceClient } from "@/lib/supabase/service";
import { Resend } from "resend";

export const maxDuration = 30;
export const dynamic = "force-dynamic";

const AGENT_NAME = "digest";
const FROM = "MarketHub Pro Maintenance <noreply@markethubpromo.com>";
const ADMIN_EMAIL = process.env.ADMIN_EMAIL ?? "markethub973@gmail.com";

interface FindingRow {
  id: string;
  agent_name: string;
  severity: "info" | "low" | "medium" | "high" | "critical";
  fingerprint: string;
  title: string;
  details: Record<string, unknown>;
  fix_suggestion: string | null;
  first_seen: string;
  last_seen: string;
  occurrences: number;
  resolved: boolean;
  resolved_at: string | null;
}

const SEVERITY_ORDER: FindingRow["severity"][] = ["critical", "high", "medium", "low", "info"];

const SEVERITY_COLOR: Record<FindingRow["severity"], string> = {
  critical: "#DC2626",
  high: "#EA580C",
  medium: "#F59E0B",
  low: "#65A30D",
  info: "#0891B2",
};

function todayDateStr(): string {
  return new Date().toISOString().slice(0, 10); // yyyy-mm-dd
}

function renderHTML(unresolved: FindingRow[], resolvedRecently: FindingRow[]): string {
  const byGroup = new Map<FindingRow["severity"], FindingRow[]>();
  for (const f of unresolved) {
    if (!byGroup.has(f.severity)) byGroup.set(f.severity, []);
    byGroup.get(f.severity)!.push(f);
  }

  const sections: string[] = [];
  for (const sev of SEVERITY_ORDER) {
    const items = byGroup.get(sev);
    if (!items || items.length === 0) continue;
    const color = SEVERITY_COLOR[sev];
    const rows = items
      .map(
        (f) => `
      <div style="border-left:4px solid ${color};padding:12px 16px;margin-bottom:12px;background:#FAFAFA;border-radius:4px;">
        <div style="font-weight:600;color:#1F2937;font-size:14px;margin-bottom:4px;">${escape(f.title)}</div>
        <div style="color:#6B7280;font-size:12px;margin-bottom:8px;">
          <span style="background:${color};color:white;padding:2px 8px;border-radius:10px;font-weight:600;">${sev.toUpperCase()}</span>
          &nbsp;·&nbsp; agent: <code>${escape(f.agent_name)}</code>
          &nbsp;·&nbsp; ${f.occurrences}× occurrences
          &nbsp;·&nbsp; first seen ${f.first_seen.slice(0, 10)}
        </div>
        ${f.fix_suggestion ? `<div style="color:#4B5563;font-size:12px;margin-top:8px;white-space:pre-wrap;"><strong>Fix:</strong> ${escape(f.fix_suggestion)}</div>` : ""}
        <div style="color:#9CA3AF;font-size:10px;margin-top:6px;font-family:monospace;">${escape(f.fingerprint)}</div>
      </div>`,
      )
      .join("");
    sections.push(`
      <h3 style="color:${color};font-size:16px;margin:24px 0 12px;border-bottom:2px solid ${color};padding-bottom:4px;">
        ${sev.toUpperCase()} — ${items.length} finding${items.length === 1 ? "" : "s"}
      </h3>
      ${rows}
    `);
  }

  const resolvedBlock =
    resolvedRecently.length > 0
      ? `
    <h3 style="color:#16A34A;font-size:16px;margin:32px 0 12px;border-bottom:2px solid #16A34A;padding-bottom:4px;">
      Resolved in the last 24h — ${resolvedRecently.length}
    </h3>
    ${resolvedRecently
      .map(
        (f) => `<div style="color:#4B5563;font-size:12px;padding:4px 0;">✓ [${escape(f.agent_name)}] ${escape(f.title)}</div>`,
      )
      .join("")}
  `
      : "";

  const emptyState =
    sections.length === 0
      ? `<div style="padding:24px;background:#D1FAE5;border-radius:8px;color:#065F46;text-align:center;">
          ✓ No unresolved findings. All maintenance agents report clean.
        </div>`
      : "";

  return `
    <div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:680px;margin:0 auto;padding:24px;background:#FFFFFF;">
      <h1 style="color:#1F2937;font-size:22px;margin-bottom:4px;">MarketHub Pro — Maintenance Digest</h1>
      <p style="color:#6B7280;font-size:13px;margin-top:0;">${todayDateStr()}</p>
      ${emptyState}
      ${sections.join("")}
      ${resolvedBlock}
      <hr style="border:none;border-top:1px solid #E5E7EB;margin:32px 0 16px;"/>
      <p style="color:#9CA3AF;font-size:11px;text-align:center;">
        Generated by the maintenance agent team ·
        <a href="https://markethubpromo.com/dashboard/admin/maintenance" style="color:#F59E0B;">view admin dashboard</a>
      </p>
    </div>
  `;
}

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function GET(req: NextRequest) {
  if (!verifyCronSecret(req, "/api/maint/digest")) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const supa = createServiceClient();
  const today = todayDateStr();

  // Idempotency: did we already send today?
  const { data: existing } = await supa
    .from("maintenance_findings")
    .select("id")
    .eq("agent_name", AGENT_NAME)
    .eq("fingerprint", `digest:${today}`)
    .maybeSingle();

  if (existing) {
    return NextResponse.json({ ok: true, skipped: "digest already sent today", today });
  }

  // Gather unresolved findings (exclude the digest agent itself)
  const { data: unresolved, error: err1 } = await supa
    .from("maintenance_findings")
    .select("*")
    .eq("resolved", false)
    .neq("agent_name", AGENT_NAME)
    .order("severity", { ascending: true })
    .order("last_seen", { ascending: false })
    .limit(200);

  if (err1) {
    return NextResponse.json({ error: "Failed to fetch findings", details: err1.message }, { status: 500 });
  }

  // Gather recently resolved (last 24h) so admin sees progress
  const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const { data: resolved } = await supa
    .from("maintenance_findings")
    .select("*")
    .eq("resolved", true)
    .gte("resolved_at", yesterday)
    .neq("agent_name", AGENT_NAME)
    .order("resolved_at", { ascending: false })
    .limit(50);

  const unresolvedList = (unresolved ?? []) as FindingRow[];
  const resolvedList = (resolved ?? []) as FindingRow[];

  // Count by severity for subject line
  const counts: Record<string, number> = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of unresolvedList) counts[f.severity] = (counts[f.severity] ?? 0) + 1;

  const subject =
    unresolvedList.length === 0
      ? `[Maintenance] ${today} — All clear`
      : `[Maintenance] ${today} — ${counts.critical} crit / ${counts.high} high / ${counts.medium} med`;

  const html = renderHTML(unresolvedList, resolvedList);

  // Send the digest email via Resend
  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json(
      { error: "RESEND_API_KEY not set — skipping send", counts, findings: unresolvedList.length },
      { status: 500 },
    );
  }

  const resend = new Resend(process.env.RESEND_API_KEY);
  const sent = await resend.emails.send({
    from: FROM,
    to: ADMIN_EMAIL,
    subject,
    html,
  });

  // Insert lock row so we don't re-send today
  await supa.from("maintenance_findings").insert({
    agent_name: AGENT_NAME,
    severity: "info",
    fingerprint: `digest:${today}`,
    title: `Digest sent ${today}`,
    details: {
      counts,
      unresolved_total: unresolvedList.length,
      resolved_recent: resolvedList.length,
      resend_id: sent.data?.id ?? null,
      resend_error: sent.error ? String(sent.error.message ?? sent.error) : null,
    },
    resolved: true, // mark the lock row resolved so it doesn't show up in future digests
    resolved_at: new Date().toISOString(),
    resolved_by: "digest-sent",
  });

  return NextResponse.json({
    ok: true,
    sent_to: ADMIN_EMAIL,
    counts,
    unresolved_total: unresolvedList.length,
    resolved_recent: resolvedList.length,
    resend_id: sent.data?.id ?? null,
    resend_error: sent.error ? String(sent.error.message ?? sent.error) : null,
  });
}
